name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: macos-latest

    steps:
      - name: Yarn Setup
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          # The version of Node.js that will be used
          node-version: 16

      - name: Publish releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx electron-builder -- --publish always --mac
          npx electron-builder -- --publish always --win
          npx electron-builder -- --publish always --linux
